/* 
 * AgentSee API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-02-13T22:19:32Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EFormsMessage
    /// </summary>
    [DataContract]
    public partial class EFormsMessage :  IEquatable<EFormsMessage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EFormsMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EFormsMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EFormsMessage" /> class.
        /// </summary>
        /// <param name="TransactionId">TransactionId (required).</param>
        /// <param name="Data">Data.</param>
        /// <param name="FormsData">FormsData.</param>
        public EFormsMessage(string TransactionId = default(string), string Data = default(string), List<FormData> FormsData = default(List<FormData>))
        {
            // to ensure "TransactionId" is required (not null)
            if (TransactionId == null)
            {
                throw new InvalidDataException("TransactionId is a required property for EFormsMessage and cannot be null");
            }
            else
            {
                this.TransactionId = TransactionId;
            }
            this.Data = Data;
            this.FormsData = FormsData;
        }
        
        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name="transactionId", EmitDefaultValue=false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets FormsData
        /// </summary>
        [DataMember(Name="formsData", EmitDefaultValue=false)]
        public List<FormData> FormsData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EFormsMessage {\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  FormsData: ").Append(FormsData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EFormsMessage);
        }

        /// <summary>
        /// Returns true if EFormsMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of EFormsMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EFormsMessage input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransactionId == input.TransactionId ||
                    (this.TransactionId != null &&
                    this.TransactionId.Equals(input.TransactionId))
                ) && 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && 
                (
                    this.FormsData == input.FormsData ||
                    this.FormsData != null &&
                    this.FormsData.SequenceEqual(input.FormsData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionId != null)
                    hashCode = hashCode * 59 + this.TransactionId.GetHashCode();
                if (this.Data != null)
                    hashCode = hashCode * 59 + this.Data.GetHashCode();
                if (this.FormsData != null)
                    hashCode = hashCode * 59 + this.FormsData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
