/* 
 * AgentSee API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2017-02-13T22:19:32Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Forms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormsTests
    {
        // TODO uncomment below to declare an instance variable for Forms
        //private Forms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Forms
            //instance = new Forms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Forms
        /// </summary>
        [Test]
        public void FormsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Forms
            //Assert.IsInstanceOfType<Forms> (instance, "variable 'instance' is a Forms");
        }


        /// <summary>
        /// Test the property 'FormNumber'
        /// </summary>
        [Test]
        public void FormNumberTest()
        {
            // TODO unit test for the property 'FormNumber'
        }
        /// <summary>
        /// Test the property 'GeoCode'
        /// </summary>
        [Test]
        public void GeoCodeTest()
        {
            // TODO unit test for the property 'GeoCode'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'S3Link'
        /// </summary>
        [Test]
        public void S3LinkTest()
        {
            // TODO unit test for the property 'S3Link'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Base64Encoded'
        /// </summary>
        [Test]
        public void Base64EncodedTest()
        {
            // TODO unit test for the property 'Base64Encoded'
        }

    }

}
